# Amazon BestSelling Books Dataset 📚

### 1. - Instalar e Exportar o Pandas & Carregar o DataFrame

In [136]:
import pandas as pd

df =pd.read_csv('../data/bestsellers with categories.csv')

### 2. - Explorar o DataFrame

In [137]:
# Printa as 5 primeiras linhas do DataFrame
display(df.head())
# Printa o número de linhas e colunas do DataFrame
display(df.shape)
# Printa os nomes das colunas do DataFrame
display(df.columns)
# Printa o resumo estatístico do DataFrame
display(df.describe())

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

(550, 7)

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='str')

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

### 3. - Limpar e Organizar o DataFrame

In [138]:
# Apagar os dados com os títulos duplicados
df.drop_duplicates(subset=['Name'], inplace=True)
# Verificar se há valores nulos em alguma coluna
display(df.isnull().sum())

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [139]:
# Verificar a quantidade de valores duplicados apagados
display(df.shape)
#Comparando com o DataFrame original o valor apagado foi 550-351 = 199 linhas duplicadas.
print(f"Quantidade de Linhas Duplicadas Apagadas: {550-351}")

(351, 7)

Quantidade de Linhas Duplicadas Apagadas: 199

In [140]:
#Renomear as colunas para português
df.rename(columns={'Name': 'Título', 'Author': 'Autor', 'User Rating': 'Avaliação do Usuário','Reviews': 'Avaliações', 'Price': 'Preço', 'Year': 'Ano', 'Genre': 'Gênero'}, inplace=True)
df['Gênero'] = df['Gênero'].replace({'Fiction': 'Ficção', 'Non Fiction': 'Não Ficção'})
display(df.head())

,Título,Autor,Avaliação do Usuário,Avaliações,Preço,Ano,Gênero
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Não Ficção
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Ficção
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Não Ficção
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Ficção
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Não Ficção

In [141]:
# Converter o tipo de dado
df['Preço'] = df['Preço'].astype(float)
df['Preço_convertido'] = df['Preço'].apply(lambda x: f"$ {x:,.2f}")
display(df.dtypes)
display(df.head())

Título                      str
Autor                       str
Avaliação do Usuário    float64
Avaliações                int64
Preço                   float64
Ano                       int64
Gênero                      str
Preço_convertido            str
dtype: object

,Título,Autor,Avaliação do Usuário,Avaliações,Preço,Ano,Gênero,Preço_convertido
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8.0,2016,Não Ficção,$ 8.00
1,11/22/63: A Novel,Stephen King,4.6,2052,22.0,2011,Ficção,$ 22.00
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15.0,2018,Não Ficção,$ 15.00
3,1984 (Signet Classics),George Orwell,4.7,21424,6.0,2017,Ficção,$ 6.00
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12.0,2019,Não Ficção,$ 12.00

### 4. Realizar Análise de Dados

In [142]:
# Titulos com mais avaliações
melhores_reviews = df.sort_values(by='Avaliações', ascending=False)
top_10_reviews =  melhores_reviews.head(10)
display(top_10_reviews[['Título', 'Autor', 'Ano', 'Avaliações']])

,Título,Autor,Ano,Avaliações
534,Where the Crawdads Sing,Delia Owens,2019,87841
382,The Girl on the Train,Paula Hawkins,2015,79446
32,Becoming,Michelle Obama,2018,61133
135,Gone Girl,Gillian Flynn,2012,57271
365,The Fault in Our Stars,John Green,2012,50482
437,The Nightingale: A Novel,Kristin Hannah,2015,49288
106,Fifty Shades of Grey: Book One of the Fifty Sh...,E L James,2012,47265
433,The Martian,Andy Weir,2015,39459
20,All the Light We Cannot See,Anthony Doerr,2014,36348
338,The Alchemist,Paulo Coelho,2014,35799

In [143]:
# Títulos com melhores avaliações dos usuários
rating_usuário = df.sort_values(by='Avaliação do Usuário', ascending=False)
top_10_rating_usuário = rating_usuário.head(10)
display(top_10_rating_usuário[['Título', 'Autor', 'Ano', 'Avaliação do Usuário']])
# Houve um empate na avaliação do usuário, vamos quantificar quantos livros tem o valor 4.9
contagem_4_9 = df[df['Avaliação do Usuário'] == 4.9].shape[0]
print(f"A quantidade de títulos com avaliação de 4.9 é: {contagem_4_9} livros 📖")

,Título,Autor,Ano,Avaliação do Usuário
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019,4.9
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,2017,4.9
87,Dog Man: Lord of the Fleas: From the Creator o...,Dav Pilkey,2018,4.9
486,The Wonderful Things You Will Be,Emily Winfield Martin,2016,4.9
476,The Very Hungry Caterpillar,Eric Carle,2013,4.9
151,Hamilton: The Revolution,Lin-Manuel Miranda,2016,4.9
153,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,2016,4.9
420,The Legend of Zelda: Hyrule Historia,Patrick Thorpe,2013,4.9
431,The Magnolia Story,Chip Gaines,2016,4.9
81,Dog Man and Cat Kid: From the Creator of Capta...,Dav Pilkey,2018,4.9

A quantidade de títulos com avaliação de 4.9 é: 28 livros 📖

In [144]:
# Títulos com maior avaliação do usuário e mais avaliações
reviews_livros = df.sort_values(by=['Avaliação do Usuário', 'Avaliações'], ascending=[False, False])
top_10_reviews_livros = reviews_livros.head(10)
display(top_10_reviews_livros[['Título', 'Autor', 'Ano', 'Avaliação do Usuário', 'Avaliações']].reset_index(drop=True))

,Título,Autor,Ano,Avaliação do Usuário,Avaliações
0,"Oh, the Places You'll Go!",Dr. Seuss,2012,4.9,21834
1,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,2016,4.9,19622
2,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,2011,4.9,19576
3,The Very Hungry Caterpillar,Eric Carle,2013,4.9,19546
4,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,2017,4.9,14344
5,Dog Man: Fetch-22: From the Creator of Captain...,Dav Pilkey,2019,4.9,12619
6,Last Week Tonight with John Oliver Presents A ...,Jill Twiss,2018,4.9,11881
7,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,2016,4.9,10052
8,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019,4.9,9413
9,Strange Planet (Strange Planet Series),Nathan W. Pyle,2019,4.9,9382

In [145]:
# Popularidade do Autor
contagem_autor = df['Autor'].value_counts()
top_10_autores = contagem_autor.head(10)
top_10_autores.index = [f"{top_10_autores.index[0]} 🥇", f"{top_10_autores.index[1]} 🥈", f"{top_10_autores.index[2]} 🥉",] + list(top_10_autores.index[3:])
print("Autores mais populares:\n")
for autor, count in top_10_autores.items():
    print(f"{autor}: {count} livros 📖")

Autores mais populares:

Jeff Kinney 🥇: 12 livros 📖
Rick Riordan 🥈: 10 livros 📖
Stephenie Meyer 🥉: 7 livros 📖
Dav Pilkey: 6 livros 📖
J.K. Rowling: 6 livros 📖
Bill O'Reilly: 6 livros 📖
Suzanne Collins: 5 livros 📖
E L James: 5 livros 📖
John Grisham: 5 livros 📖
Stephen King: 4 livros 📖

In [146]:
# Qual ano teve mais livros publicados
contagem_anos = df['Ano'].value_counts()
print("Ano com mais livros publicados:\n")
for year, count in contagem_anos.items():
    print(f"{year}: {count} livros 📚")

Ano com mais livros publicados:

2009: 50 livros 📚
2010: 40 livros 📚
2013: 33 livros 📚
2011: 31 livros 📚
2018: 30 livros 📚
2015: 30 livros 📚
2016: 28 livros 📚
2012: 28 livros 📚
2017: 27 livros 📚
2019: 27 livros 📚
2014: 27 livros 📚

In [147]:
# Média de preço total dos livros
media_preço = df['Preço'].mean()
print(f"A média geral de preços dos livros é: $ {media_preço:.2f} 💵")

A média geral de preços dos livros é: $ 13.08 💵

In [148]:
# Média de preços por genero dos livros
media_preço_ficção = df[df['Gênero'] == "Ficção"].groupby('Gênero')['Preço'].mean().loc["Ficção"]
media_preço_não_ficção = df[df['Gênero'] == "Não Ficção"].groupby('Gênero')['Preço'].mean().loc["Não Ficção"]
print(f"Média de preços para Ficção: ${media_preço_ficção.round(2)} 💵")
print(f"Média de preços para Não Ficção: ${media_preço_não_ficção.round(2)} 💵")

Média de preços para Ficção: $12.16 💵
Média de preços para Não Ficção: $13.85 💵

In [149]:
# Média de Avaliação por Gênero
media_avaliação_ficção = df[df['Gênero'] == "Ficção"].groupby('Gênero')['Avaliação do Usuário'].mean().loc["Ficção"]
media_avaliação_não_ficção = df[df['Gênero'] == "Não Ficção"].groupby('Gênero')['Avaliação do Usuário'].mean().loc["Não Ficção"]
print(f"Média de avaliações para Ficção: {media_avaliação_ficção.round(2)} ⭐")
print(f"Média de avaliações para Não Ficção: {media_avaliação_não_ficção.round(2)} ⭐")

Média de avaliações para Ficção: 4.62 ⭐
Média de avaliações para Não Ficção: 4.6 ⭐

### 6. - Exportar os resultados do DataFrame

In [150]:
# Exportar os tops 10 autores mais populares para um arquivo txt
autor_counts.head(10).to_csv('../data/top_10_autores.txt', header=True)
# Exporta a lista de livros com maior avaliação do usuário e mais avaliações para um arquivo csv
reviews_livros.to_csv('../data/top_livros_por_avaliação.csv', index=False)